### ISSUE TITLE
without Redis

### ISSUE THREAD

**Issue by Portal2001** [NextDevv/AutoMod#1]
it is not possible to use this plugin without Redis? as the plugin just shuts itself

**Comment by NextDevv** [comment]
As I stated on <a href="https://www.spigotmc.org/threads/automod.649456/#post-4743161">my response on spigot.org</a>, yes it is possible! Here's how you can do it:

In the latest `config.yml` there's the propriety `requiresMultiInstance`, that you can set it to **false** if you don't use multiInstance servers.

Here's an example config:
```YAML
# Redis URI. If you are running multiple instances of this plugin, set this to the same URI.
redisUri: "redis://localhost"
# If you are running multiple instances of this plugin, set this to true. This will enable Redis pub/sub.
requiresMultiInstance: false # false if you don't want redis

. . .
```
